# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0
#
# This file contains selected Kconfig options for the application.

CONFIG_GPIO=y
CONFIG_PWM=y
CONFIG_SMF=y
<<<<<<< HEAD

=======
>>>>>>> 04b671780342e4c799ea3c565aaf47354aee2dda
